version: '3'

services:
  api:
    container_name: AI_Resume_Analyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=true
    restart: unless-stopped
    volumes:
      - .:/app